---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: db
    owner: kbr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      name: mydb-pod
      labels:
        app: db
    spec:
      containers:
        - name: mydb
          image: mysql
          env:
            - name: MY_SQL_ROT_PASSWORD
              value: mysql
          resources:
            requests:
              cpu: 100m
              memory: 64M
            limits:
              cpu: 200m
              memory: 120M

...
