---
apiVersion: v1
kind: Pod
metadata:
  name: postgress-db
  labels:
    app: db
    author: intellqit

spec:
  containers:
    - name: mypostgress
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: mysql
        - name: POSTGRES_USER
          value: intellqit
        - name: POSTGRES_DB
          value: mydb

...
