---
apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-rc
  labels:
    app: webserver

spec:
  replicas: 3
  template:
    metadata:
      name: htppd-pod
      labels:
        app: webserverr
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 9090
          resources:
            request:
              cpu: 100m
              memory: 6m

            limits:
              cpu: 200m
              memory: 124m



